# Generated by Django 2.0.7 on 2018-10-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deauthorized', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_token',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_token',
            field=models.TextField(unique=True, verbose_name='id token'),
        ),
    ]
